version: '3.2'
services:
  app:
    image: auth-ms
    ports:
      - 8080:8080
    environment:
      DB_PASSWORD: your_db_password
      DB_URL: jdbc:postgresql://db:5432/seed_db
      DB_USER: your_db_user
      JWT_SECRET: your_jwt_secret
      JWT_VALIDITY: your_jwt_validity
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SENTRY_DSN: your_sentry_dsn
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: appservice
