version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: seed_password
      POSTGRES_DB: seed_db
      POSTGRES_USER: seed_user
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: appservice
